version: '3.5'

services:
  hello-world:
    container_name: hello-world-${APP_ENV:-dev}
    build:
      context: .
      dockerfile: .docker/hello-world/Dockerfile
      target: ${APP_ENV:-dev}
    environment:
      APP_ENV: ${APP_ENV:-dev}
    ports:
      - ${APP_PORT:-80}:80
    volumes:
      - ./var/log:/var/log