version: '3.5'

services:

  database:
    container_name: database
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - ${DATABASE_PORT:-3306}:3306
    volumes:
    - ./data:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHP_MY_ADMIN_PORT:-8080}:80
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_PORT: ${DATABASE_PORT:-3306}
    links:
      - database:db