version: '3.5'

services:

  database:
    container_name: database
    build: docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PMA_PASSWORD:-root}
    restart: always
    ports:
      - ${PMA_PORT:-3306}:3306
    volumes:
      - ./data:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: ${PMA_USER:-root}
      PMA_PASSWORD: ${PMA_PASSWORD:-root}
      PMA_PORT: ${PMA_PORT:-3306}
    links:
      - database:db
    ports:
      - ${HOST_PORT:-8080}:80
